### ISSUE TITLE
Mismatch between "filter" tip counts and actual tip counts

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#596] opened 2018-07-18 19:19 UTC
@jameshadfield ---

@alliblk just discovered this. You can see this issue manifested in live Zika:

![zika](https://user-images.githubusercontent.com/1176109/42902727-747e6b76-8a84-11e8-93d2-667ecfacfa4c.png)

where filters report there being 78 Singapore tips, but there's really 41.

Likewise, for mumps:

![mumps](https://user-images.githubusercontent.com/1176109/42902899-f9291a1a-8a84-11e8-84ce-b7a99cbff6bb.png)

filters report there being 275 Massachusetts tips, but there's really 145.

I looked through live `meta.json`s and couldn't figure out why 78 and 275 were being reported.

**Comment by jameshadfield** [comment] 2018-07-18 19:47
Hmm. Could be due to https://github.com/nextstrain/auspice/commit/6e8edad6c53e521e7adf1cda5ed9ac6f1c76ed00 -- @alliblk does the problem exist in earlier commits?

**Comment by alliblk** [comment] 2018-07-18 20:54
I'm not sure about earlier commits, I just noticed the discrepancy today. What I do notice though is that the issue isn't there when I serve nextstrain locally, but it does exist on live. For reference my local repo is currently up to date with origin/master.

**Comment by jameshadfield** [comment] 2018-07-18 22:22
OK, thanks @alliblk .  It must be some problem with the S3 data files then (since origin/master JS code is identical to current nextstrain.org). It should be fixed by pushing new builds to S3 🎉

**Comment by trvrb** [comment] 2018-07-18 23:35
I can confirm that this issue was created by commit 6e8edad6c53e521e7adf1cda5ed9ac6f1c76ed00. Prior to this commit counts match. Alongside this commit, counts diverge.

**Closed** 2018-07-19 00:17 UTC
Labels: bug

**Comment by alliblk** [comment] 2018-07-19 18:46
Hi @jameshadfield, I'm on `901404defeb1cde344d8155f8ba644c9c8b514b5`.

**Comment by jameshadfield** [comment] 2018-07-19 19:43
@alliblk that's 22 days old... try running `git pull`!

**Comment by alliblk** [comment] 2018-07-19 19:53
Whoops, looks like one of new lock jsons was blocking the pull. Not sure why git status was saying I was up to date with origin/master then, but it's always a possibility that I'm misunderstanding how git assesses that. I stashed and re-pulled. Should be good now.

**Comment by trvrb** [comment] 2018-07-19 20:00
@alliblk: I'd recommend using GitKraken to keep track of repository state. I have repos favorited and then it's super fast to swap between them. In this case, you needed to run "git fetch" to update your local version of origin/master.
