### ISSUE TITLE
Reset map zoom doesn't take into account filters

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#863] opened 2020-01-30 00:34 UTC
Take a look at https://nextstrain.org/ncov?f_country=China&r=location. This should "reset" to just the locations in China and be zoomed appropriately. 

~However, "reset zoom" zooms way out, I believe because it's trying to include all three sets of lat/longs (both the central, but also the left-shifted and right-shifted locations). I suspect the fix here is to only use the central set of lat/longs when calculating default bounds.~

I first thought this was `map_triplicate`. It's not, reset zoom works with map triplicate as it should. However, it doesn't seem to take into account filtered state.

**Comment by jameshadfield** [comment] 2020-01-30 02:28
> However, it doesn't seem to take into account filtered state.

This is my understanding. I'm hesitant to devote too much time to this right now (I don't think it's high priority) as work here is generally not "quick and easy", but this would be a nice feature. 

One thing we may want to think about is automatically zooming to include all visible demes when you select a filter (this is particularly annoying if you've already manipulated the map pan/zoom). I remember @emmahodcroft writing some things about this a while back.

**Comment by emmahodcroft** [comment] 2020-01-30 10:24
Yes, reset zoom doesn't take into account filters. (It's not a bug, it just never was programmed that way.) The workaround for this is to create different geographic locations (ex: `division_china`) that only contain the locations you want to zoom to (only contain the regions in China in this column). You can then switch to *that* geo resolution in map options (or via URL) and click 'Reset Zoom'. Then it'll work.

I recognise this isn't a perfect solution but in particular for Narratives, it'll do the trick.

I defer to James if he thinks this isn't so easy to fix, but I'll try to have a quick look today.

**Comment by emmahodcroft** [comment] 2020-01-30 14:07
Think I've got this working! 😄 I'll make a PR soon.

(Not automatic as James says - I'm hesitant about automatic things when not in Narratives as it can be super annoying - but we can discuss this more and maybe implement in a 'smart' way as James says, like if user hasn't otherwise touched map.)

I am enjoying being back working on auspice so much! 😆

**Comment by trvrb** [comment] 2020-01-30 15:44
Awesome! Thanks Emma. I agree to not automatically zoom the map when activating filters. Just like how the tree doesn't zoom to filtered tips.

**Comment by jameshadfield** [comment] 2020-01-31 06:32
Will be closed by #870

**Comment by jameshadfield** [comment] 2020-02-05 03:49
Closed by #886

**Closed by jameshadfield** 2020-02-05 03:49 UTC
