### ISSUE TITLE
Map bounds show hysterisis in narratives 

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#946] opened 2020-03-13 07:08 UTC
This issue occurs in narratives, where approaching a page from one direction causes the map bounds to be different from approaching the same page from the other direction. This is best explained in a GIF!

![map_hysterisis](https://user-images.githubusercontent.com/8350992/76597849-52e48900-6566-11ea-94b0-f5b9106c0b06.gif)

Steps to reproduce:
1. [Install auspice from source](https://nextstrain.github.io/auspice/introduction/install#installing-from-source)
2. Obtain hCoV-19 datasets & narratives via cloning github.com/nextstrain/ncov
3. Run auspice via `auspice develop --datasetDir <ncov/auspice> --narrativeDir <ncov/narratives>`

Run the latest narrative (currently unpublicised) via http://localhost:4000/narratives/ncov/sit-rep/2020-03-13?n=6. Go to the following page and then return to page 6. Note how the map bounds have changed.

**Comment by eharkins** [comment] 2020-04-24 00:12
Closing this as I am unable to reproduce in the latest version of Auspice (2.13.0). @CameronDevine if you are able to reproduce this issue, could you please re-open and point to a narrative that reproduces the problem as you experience it?

If it seems fixed to you, go ahead and close #958 as well.

Thanks!

**Comment by CameronDevine** [comment] 2020-04-24 00:19
@eharkins, This is still an issue. To reproduce use the following steps,

1. Go to https://nextstrain.org/narratives/ncov/sit-rep/2020-03-13?n=3
1. Note the bounds of the map ![image](https://user-images.githubusercontent.com/10394896/80161794-5c5e0980-8586-11ea-81c2-7459741f226d.png)
1. Scroll to the next page
1. Scroll to the previous page
1. Note the bounds of the map have changed. ![image](https://user-images.githubusercontent.com/10394896/80161816-70a20680-8586-11ea-844c-b92bd643cbd5.png)

**Comment by jameshadfield** [comment] 2020-04-24 00:31
👍 thanks @CameronDevine, this does seem to be reproducible. (I'd think it's got something to do with `mapTriplicate` deep down). Spinning up a review app to test.

**Closed** 2020-05-18 23:16 UTC
Labels: low priority, narratives
