### ISSUE TITLE
Console reports dozens errors: `Error: <path> attribute d: Expected number, " M 5,NaN L 5,NaN".`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1647] opened 2023-03-16 10:47 UTC
### Current Behavior
When loading the following tree in auspice.us (2.45.0) the console reports 2 errors:

```console
Error: <path> attribute d: Expected number, " M 5,NaN L 5,NaN".
```

When I zoom into a branch, I get dozens more, quite an error flood:

![image](https://user-images.githubusercontent.com/25161793/225593036-baba4a80-e664-44dd-af71-ad69f979d6f4.png)

These errors seem to have no obvious impact on usability. So this could be false positives.

However, the flood of false positives makes it harder to identify true errors.

### Expected behavior

No false positive console errors. As a workaround these could be caught and bubbled as one single warning.

### How to reproduce
Steps to reproduce the current behavior:
1. Open the following tree in auspice.us https://gist.githubusercontent.com/corneliusroemer/9e18bd1063aec873f654d1d7b170dd09/raw/7c88e167a507457646c5e69cb9acd999b5e7316a/gistfile0.txt
2. Open console (F12)
3. Observe errors
4. Zoom into branch, observe more errors

### Your environment: if browsing Nextstrain online
 - Operating system: macOS 13.2
 - Browser: Brave
 - Auspice 2.45.0

### Additional context

This error appears in Nextclade, too. It seems to be a long standing issue according to @ivan-aksamentov

**Comment by jameshadfield** [comment] 2023-03-28 02:08
Do you remember which branch you clicked, by chance? I can't reproduce this (auspice.us or auspice itself) after clicking some random branches

**Comment by ivan-aksamentov** [comment] 2023-03-28 08:29
@jameshadfield 

https://user-images.githubusercontent.com/9403403/228176864-be1574b0-6901-4831-a16f-722badab2f7f.mp4

**Comment by ivan-aksamentov** [comment] 2023-03-28 08:37
> So this could be false positives.
This is definitely not false positives. The actual `path` tags have the actual `NaN` values. Browser tries to be friendly and tells that it's not something it can render. There could be some visual defects that are not immediately seen with the naked eye on a complex SVG like that.


![01](https://user-images.githubusercontent.com/9403403/228178729-db73bd23-ea00-4fb1-bacb-8ed4a3b42d10.png)


There is a warning about missing `geoResolutions`. Which may or may not be related. Because Nextclade generates the tree JSON on its own, we might be behind the latest developments in the sweet Augur/Auspice couple, and might not emit some of the required fields or emit them in a wrong format.

**Comment by ivan-aksamentov** [comment] 2023-03-28 08:50
Here is the full console log (from another session, not the same as on the video, bus similar)
[auspice.us-1679993203362.log](https://github.com/nextstrain/auspice/files/11087314/auspice.us-1679993203362.log)
The function names are not particularly comprehensible though, so cannot tell much.

**Comment by ivan-aksamentov** [comment] 2023-03-28 08:55
But here is the log from Nextclade, from the similar situation. Repro: Open dev console, navogate to Nextclade, select SC2 dataset, hit "Load example", then "Run", (or navigate to https://clades.nextstrain.org/?dataset-name=sars-cov-2&input-fasta=example for the same effect), then hit the "tree" button.

[clades.nextstrain.org-1679993358555.log](https://github.com/nextstrain/auspice/files/11087353/clades.nextstrain.org-1679993358555.log)

In Nextclade we have source maps setup differently, so there seems some more debug info about functions involved. In case it helps.

**Comment by jameshadfield** [comment] 2023-03-29 05:01
Oh fun! It seems Firefox just doesn't print this kind of error to the console, whereas Safari & Chrome do. (The `NaN` is still present in Firefox, so at least it's not _that_ kind of browser-dependent behaviour!)

**Comment by victorlin** [comment] 2023-10-19 22:41
I also keep seeing this so I traced it down. For the rectangular tree view, it comes from y values in the paths defined [here](https://github.com/nextstrain/auspice/blob/2e5792bf1044ffa629c7249d2c17ef8f8708fbe0/src/components/tree/phyloTree/layouts.js#L484-L487). Those are based on attempts to get `yScale` values using `node.y`, `node.py`, and `node.displayOrderRange[0]`/`[1]`. It turns out, all those values are `undefined` for the first node because `displayOrder`-related values on that node are [set to `undefined`](https://github.com/nextstrain/auspice/blob/2e5792bf1044ffa629c7249d2c17ef8f8708fbe0/src/components/tree/phyloTree/helpers.js#L97-L99) and [`y`/`py` are based on `displayOrder`](https://github.com/nextstrain/auspice/blob/2e5792bf1044ffa629c7249d2c17ef8f8708fbe0/src/components/tree/phyloTree/layouts.js#L58-L61).

Fix is in the PR linked above.

**Closed** 2023-10-19 22:42 UTC
Labels: bug
