### ISSUE TITLE
Show mutation split into homoplasic/unique/reversions also on terminal branches, not just internal ones

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1752] opened 2024-02-16 16:05 UTC
### Context
The Auspice feature to split mutations on branches into: homoplasic, unique, and reversions is very useful.

I noticed that this feature is not available for terminal branches. I can't see a reason why we shouldn't use the same feature for those branches, it's just as useful there.

See internal:
<img width="710" alt="image" src="https://github.com/nextstrain/auspice/assets/25161793/9992c5c4-9c81-497d-96ab-272a3f1daf76">

Vs. terminal:
<img width="735" alt="image" src="https://github.com/nextstrain/auspice/assets/25161793/fbf3643e-35cc-4b3b-ab71-11ed10ed6eb5">

**Comment by FedeGueli** [comment] 2024-02-17 23:01
@corneliusroemer @ryhisner i think it was available until friday and now it changed and it has been removed.. if this is correct it is really a pain for us regularly checking singlets everyday maybe @ryHisner could add his point

**Comment by ryhisner** [comment] 2024-02-17 23:14
Terminal-branch mutations have always been visible. They just suddenly disappeared a day or two ago, and I REALLY miss them. It's hard to express just how much harder it is for me to do what I usually do without being able to view them. I've already wasted hours trying to sort out the mutations on long branches—something I used to be able to do quickly because shift-clicking the branch showed them immediately.

**Comment by ryhisner** [comment] 2024-02-17 23:18
I noticed that even the 21L tree has changed—you can no longer view the mutations on terminal branches by shift-clicking. Since there's no option to label branches with nucleotide mutations, it's extremely difficult to tell what synonymous (or non-synonymous ORF9b) mutations a terminal branch has.
<img width="1320" alt="image" src="https://github.com/nextstrain/auspice/assets/33738461/55635a3d-a15f-425a-846d-c46d93fc2c4a">

**Comment by corneliusroemer** [comment] 2024-02-18 06:49
Thanks guys for suggesting this is a regression and that this happened recently.

It should be easy to revert for @jameshadfield - as it's not in the changelog I don't think it was intended.

**Comment by FedeGueli** [comment] 2024-02-18 07:57
> Thanks guys for suggesting this is a regression and that this happened recently.
> 
> It should be easy to revert for @jameshadfield - as it's not in the changelog I don't think it was intended.

Thank you @corneliusroemer @jameshadfield

**Comment by corneliusroemer** [comment] 2024-02-19 20:41
I can confirm this is indeed a regression introduced between 2.51.0 and 2.52.0

This is 2.51.0 (`npx auspice@2.51.0`):
<img width="1332" alt="image" src="https://github.com/nextstrain/auspice/assets/25161793/3ee4c034-d24d-4ef0-95a5-55a289b3a8ee">

This is 2.52.0 (`npx auspice@2.52.0`):
<img width="1412" alt="image" src="https://github.com/nextstrain/auspice/assets/25161793/d466d3a0-5573-4056-8972-57b705dbea7e">

**Comment by FedeGueli** [comment] 2024-02-19 21:56
> I can confirm this is indeed a regression introduced between 2.51.0 and 2.52.0
> 
> This is 2.51.0 (`npx auspice@2.51.0`): <img alt="image" width="1332" src="https://private-user-images.githubusercontent.com/25161793/306069272-3ee4c034-d24d-4ef0-95a5-55a289b3a8ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzk5NDIsIm5iZiI6MTcwODM3OTY0MiwicGF0aCI6Ii8yNTE2MTc5My8zMDYwNjkyNzItM2VlNGMwMzQtZDI0ZC00ZWYwLTk1YTUtNTVhMjg5YjNhOGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDIxNTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NDEzNGIwY2JmZjgzMWI1MzcyNDU1ZmEwNDlmMWEzYjA2MjZlM2MyZGE2ZTNiYjE1MzNjNTY0NmMxNTM3YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r_Rf6PAG--Ums-aSE8vaK31zW2qdgYthWsUJakjI0cE">
> 
> This is 2.52.0 (`npx auspice@2.52.0`): <img alt="image" width="1412" src="https://private-user-images.githubusercontent.com/25161793/306069327-d466d3a0-5573-4056-8972-57b705dbea7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzk5NDIsIm5iZiI6MTcwODM3OTY0MiwicGF0aCI6Ii8yNTE2MTc5My8zMDYwNjkzMjctZDQ2NmQzYTAtNTU3My00MDU2LTg5NzItNTdiNzA1ZGJlYTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDIxNTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNDBhMTVlOWNhMzRmZThhNjhlNmIxYTZhYjQ0NzI1ODgyYzExMTMzNTdjNjhkNWZhMzAwNDI1NzUwZDEwOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mepH6396DI81qIDrzIdizc9wfk624X-L2k1c50kxIUg">

Thank you Cornelius as variant spotter that slows very much or disable our work efficiency . I know nextstrain is much more important than for our goals, but it is also a time where there aren't many people doing spotting systematically so it would be very important this will be fixed soon. thank you very much for your help.

**Comment by ryhisner** [comment] 2024-02-20 11:13
Is a fix for this in the works? I'm trying workarounds to be able to figure out all the mutations on terminal branches, but they all require a lot more time.

**Comment by corneliusroemer** [comment] 2024-02-20 13:00
Using auspice/auspice.us 2.51.0  would work - though you'd have to host them locally AFAIK

**Comment by jameshadfield** [comment] 2024-02-20 22:39
I've fixed this in PR #1753. I'll merge shortly and make a new Auspice release (2.52.1) and push this over to nextstrain.org. It should be available in the next few hours if all goes smoothly.

**Comment by FedeGueli** [comment] 2024-02-20 22:40
> I've fixed this in PR #1753. I'll merge shortly and make a new Auspice release (2.52.1) and push this over to nextstrain.org. It should be available in the next few hours if all goes smoothly.

Wow! great news thank you very much!

**Closed** 2024-02-20 23:55 UTC
Labels: bug, regression

**Comment by jameshadfield** [comment] 2024-02-21 00:12
This issue has been closed because the PR has been merged, but the fix is yet to propagate to nextstrain.org. I'll write a message here when this happens.

For those interested in what happened, a recent PR (#1749) inadvertently removed the distinction between terminal _branches_ and _tips_, which resulted in hovering or shift-clicking on terminal branches showing the wrong information. The intended behaviour is for hovering/shift-clicking on a branch to summarise the changes on that individual branch, whereas hovering/clicking on the tip should show information about the specific strain and (e.g.) collect all mutations between the tip and the tree root.

**Comment by jameshadfield** [comment] 2024-02-21 01:38
Changes released with Auspice 2.52.1, and nextstrain.org is updated. If you are still getting the old version (as shown in the page footer) please try refreshing the page holding the shift key.

**Comment by FedeGueli** [comment] 2024-02-21 06:16
> This issue has been closed because the PR has been merged, but the fix is yet to propagate to nextstrain.org. I'll write a message here when this happens.
> 
> For those interested in what happened, a recent PR (#1749) inadvertently removed the distinction between terminal _branches_ and _tips_, which resulted in hovering or shift-clicking on terminal branches showing the wrong information. The intended behaviour is for hovering/shift-clicking on a branch to summarise the changes on that individual branch, whereas hovering/clicking on the tip should show information about the specific strain and (e.g.) collect all mutations between the tip and the tree root.

Thank you for the explanation and for the tip !

**Comment by ryhisner** [comment] 2024-02-21 11:58
> I've fixed this in PR #1753. I'll merge shortly and make a new Auspice release (2.52.1) and push this over to nextstrain.org. It should be available in the next few hours if all goes smoothly.

You guys are awesome! Thanks so much!

**Comment by corneliusroemer** [comment] 2024-02-21 13:26
Thanks @jameshadfield!
