### ISSUE TITLE
Unescaped quotes in downloaded TSV file

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/auspice#1648] opened 2023-03-15 14:35 UTC
### Current Behavior
Some acknowledgement files cannot be read correctly into Excel (and also sometimes R, depending on quote settings), with rows going 'missing'. 
An acknowlegement file downloaded from [23A.Omicron focal build](https://nextstrain.org/groups/neherlab/ncov/23A.Omicron) on 14 Mar (the build has since been updated, haven't tried the newer file) contains 6346 sequences & examining the resulting acknowledgement file in Visual Studio Code shows it also has 6347 lines (including header).

However, if the file is opened in Excel it seems to have 5308 lines (including header) and if read into R with `read.csv(...quote="\'")` (allowing `"` to quote leads to an EOF error) results in 3224 rows (excluding header).

This is confusing to users.

### Expected behavior
Downloaded acknowledgement files should have as many rows/lines as sequences in the downloaded set.

### How to reproduce
Steps to reproduce the current behavior:
1. At least on the 15 Mar 23, download acknowledgements files from [23A.Omicron build](https://nextstrain.org/groups/neherlab/ncov/23A.Omicron) -- should have 6567 sequences
2. Drag-and-drop into blank Excel 
3. Scroll to see number of lines - is 5623

### Possible reason
For unclear reasons, sometimes originating & submitting labs and authors can be surrounded by double-quotes in GISAID:
![image](https://user-images.githubusercontent.com/14290674/225336540-4d14b1ee-f141-400b-8266-ca8f9078ca30.png)
This (unclosed `"`) happens at least 17 times in a dataset of 6300 seqs, so it's not so uncommon. 
I haven't seen any signs it also happens with single quotes, but I can't rule it out entirely

When this happens with originating/submitting labs, this doesn't seem to be an issue - they come out with the quotes. However, for authors, if we then want to shorten to `et al` ending (as we do [here](https://github.com/nextstrain/ncov-ingest/blob/59b2a36171d8379a284abb21f450f8c640e38c28/lib/utils/transformpipeline/transforms.py#L370)), this replaces the end, leaving a hanging `"`. 
From the above example, it goes from:
`"Sylvanus Okogbenin, Cyril Erameh, Sophie Duraffour, Stephan Guenther"`
to
`"Sylvanus Okogbenin et al`

### Possible solution
We should either decide to:
1. Strip all quotes entirely (could displease places that would prefer to have internal quotes, ex `Mühlenkreiskliniken Standort Minden: Institut für Laboratoriumsmedizin Mikrobiologie Hygiene und Transfusionsmedizin; wird auch unter dem Namen "LaborZentrum Weser" geführt`)
2. Strip all leading/ending quotes before any further transformation (could lead to more issues without careful matching- example `RSE "National Center of Expertise" and RSE "National center for Biotechnology"` (ending quote, but no leading quote)), 
3. Remote all quotes from Authors only
4. Add a trailing quote back in when converting to `et al.` for Authors.

**Comment by tsibley** [comment] 2023-03-17 18:04
@joverlee521 Thanks for moving this to Auspice!

Indeed, the issue is that Auspice is doing a naive join on tabs instead of using a proper TSV producer:

https://github.com/nextstrain/auspice/blob/af735389ea8125e74c84008a7600c1f2c80512c5/src/components/download/helperFunctions.js#L318-L331

**Comment by joverlee521** [comment] 2023-03-17 18:45
I'll try changing the naive join to `Papa.unparse` since we already have `papaparse` as a dependency for parsing CSVs.

**Comment by emmahodcroft** [comment] 2023-03-20 10:32
Thanks for catching the real source Jover, and apologies for the false-start!

**Closed** 2023-03-20 22:18 UTC
Labels: bug
