### ISSUE TITLE
nCoV animation should be smooth

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#918] opened 2020-03-05 00:40 UTC
This is due to us hardcoding some minimum amount of time to be shifted each tick. The tree is small enough that it should be animating super smoothly.

**Comment by trvrb** [comment] 2020-03-05 00:45
I'd love this fixed. Take a look at how smooth this is: https://nextstrain.org/zika?animate=2005-12-15,2019-07-06,1,0,30000&p=grid and compare to this https://nextstrain.org/ncov?animate=2005-12-15,2019-07-06,1,0,30000&p=grid.

**Comment by dnprock** [comment] 2020-03-05 06:54
I'm not able to test with ncov dataset to see the behavior. I looked at this animation code. I think the choppy behavior is caused by remove/add of the temporal windows. When the code removes/adds svg rect, we see the choppy animation.

https://github.com/nextstrain/auspice/blob/master/src/components/tree/phyloTree/grid.js#L338

I suggest instead of using remove/add, you use d3.transition. That can help smooth out the animation.

I can play around with it when I have some time.

**Comment by hydrosquall** [comment] 2020-03-05 07:36
+1 to @dnprock 's observation that modifying the `animationTick` didn't have a noticeable impact on the observed smoothness of the animation (I had been looking into this issue prior to seeing their comment). 

The issue seemed to me that the jumps between adjacent "rectangle" positions are fundamentally much larger when the `totalDatasetRange` is small, as is the case with the ncov sample (which spans months), whereas the Zika example linked above spans years. This is because the smallest granularity that can be encoded in the URL is at the "days" level of resolution. Changing that behavior (representing sub-day timestamps) seems out of scope for the PR, so representing those intermediary x coordinates with d3 transition instead of more granular dates seems reasonable.

https://github.com/nextstrain/auspice/blob/eaa847fb0e8c22bbea275bb604b5268567eaa332/src/actions/recomputeReduxState.js#L88-L95

After figuring this out, I took a pass at the d3.transition based approach. It's working with a local copy of the ncov dataset using the following commands, but I'm not sure how to test a "right hand tree", so some tweaks may be needed to support that usecase. Here's a video clip (and the steps to reproduce this setup locally once you've cloned my branch): https://a.cl.ly/jkuKeJn7

```bash
mkdir data
curl http://data.nextstrain.org/ncov.json --compressed -o data/ncov.json
node auspice view --datasetDir data
```

**Closed** 2020-04-08 07:04 UTC
Labels: bug, good first issue, high priority, please take this issue
