### ISSUE TITLE
Improve matching algorithm of filter UI

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1233] opened 2020-11-19 02:37 UTC
The filter search box (see https://github.com/nextstrain/auspice/pull/1200) currently matches on the [label key](https://github.com/nextstrain/auspice/blob/master/src/components/controls/filter.js#L99). Values of these look like
```
country → USA
country → South Africa
country → New Zealand
...
```

The matching algorithm behind React Select seems to require complete matching of the provided string in that list (case insensitive). So, for instance, `new zealand` matches fine, however `country new zealand` doesn't (`country → new zealand
` would be required). This should be improved.

**Comment by joverlee521** [comment] 2022-02-18 23:49
Duplicate of https://github.com/nextstrain/auspice/issues/1271

**Closed by joverlee521** 2022-02-18 23:49 UTC
