### ISSUE TITLE
ENH: Show AA position when selecting AA mutations in entropy panel

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/auspice#1571] opened 2022-10-18 14:51 UTC
### Context
Jesse made a nice plot that could be made very easily with Auspice's entropy panel.

However, I noticed a few things that make the entropy panel not so great for direct usage:
1. We always show nucleotide positions even when `AA` is selected. It would be nice if we switched numbering to `AA` positions when switching from nt to AA, or at least allow users to toggle, or maybe show both.

2. Showing the gene map above the x-axis labels is a bit confusing. If I just want to show spike, I wouldn't want all the other genes visible.

<img width="1644" alt="image" src="https://user-images.githubusercontent.com/25161793/196465049-4b3b7fa2-3bec-4435-98ae-4ce9461a404a.png">

This is Jesse's plot:
https://twitter.com/jbloom_lab/status/1582381259783012352?s=20&t=e_NAjZJ8RSFpcyBUuX-zwg

**Comment by jameshadfield** [comment] 2022-10-19 01:53
Big yes for (1), although there are complications to think through such as overlapping genes. In general, making a robust genome viewers is complicated not because of programming but because of biology. I've largely avoided it in auspice, and thus our viewer is pretty simple. I think we could do something like rendering a aa-labelled axis under each gene (in the upper track of your screenshot), but again the complication comes not with your example but when we have overlapping genes etc.

For (2) you could just crop out the bottom (entire genome) bit, could you not?

**Comment by corneliusroemer** [comment] 2022-10-19 16:22
Gotcha @jameshadfield thanks for explaining.

Maybe we could make something that works in 80% of cases and can be switched on, so that it doesn't need to work in 100% of cases.

You're right re 2), I can juts crop it out. Not sure what I was thinking...

**Comment by jameshadfield** [comment] 2022-10-20 00:58
Duplicate of https://github.com/nextstrain/auspice/issues/299 - let's move discussion over there.

**Closed by jameshadfield** 2022-10-20 00:58 UTC
Labels: enhancement
