### ISSUE TITLE
Firefox working but Chrome displays error 404 for the same URL

### ISSUE THREAD

**Issue by xiaoyu518** [nextstrain/auspice#1499] opened 2022-04-07 10:56 UTC
### Current Behavior
I have a remote auspice server running. Chrome displays the 404 error (Couldn't load JSONs for pol/20210524) specifically for one JSON file while another two JSON files works fine in Chrome. 

### Expected behavior
Firefox works perfectly for all files.  

### How to reproduce
Running the URL http://visualisations.pangea-hiv.org/ with Chrome and Firefox. pol/20210524 and narratives/IntroToPANGEADashboard are having issues with Chrome while others are working.

### Possible solution
I dont think it is an issue with the file itself as it works in firefox. It may have something to do with the Chrome itself however I dont have the expertise to debug this issue. Auspice did not give any errors while attempting to load the problematic files through chrome.

### Your environment: if browsing Nextstrain online
 - Operating system: Mac
 - Browser: Firefox/Chrome

**Comment by joverlee521** [comment] 2022-04-07 20:32
Hi @xiaoyu518, 

Chrome's error console only displays a very generic message
```
SyntaxError: Unexpected end of JSON input 'Unexpected end of JSON input'
```
Since the same dataset works on Firefox, you are correct that this is not an issue with the JSON file. I think this is most likely due to Chrome's limits on memory usage. `pol/20210524` is close to 600MB while the other datasets are less than 500MB. `narratives/IntroToPANGEADashboard` uses `pol/20210524` as the default dataset so it would not load due to the memory limits as well. 

I inspected the JSON file and noticed that it includes indentation and line returns. If you generated the JSONs using [augur export](https://docs.nextstrain.org/projects/augur/en/stable/usage/cli/export.html), I recommend using the `--minify-json` option to export the JSONs without indentations and line returns to reduce the size of the file. 

Closing the issue because it is not a bug in Auspice.

**Closed by joverlee521** 2022-04-07 20:32 UTC
Labels: bug
