### ISSUE TITLE
zoom to clade bugs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#142] opened 2017-01-26 02:26 UTC
(1) When zoomed into a clade, now zoom out - the gridlines / axis are restricted to the zoomed in view

(2) subsequent "zoom to clade" do not zoom to the correct bounds

(3) do not allow to zoom if leaf branch selected

**Comment by trvrb** [comment] 2017-02-07 01:41
(3) has been resolved in 939725a7ab980fd88998a8d7044aa73ee93eaeea.

**Comment by rneher** [comment] 2017-02-17 20:50
part of the issue is that clade zoom and viewport zoom don't play nicely together. viewport zoom will result in grid labels out of viewport. don't see a solution other than lifting the grid from the tree. but I also don't think its a pressing issue. viewport and clade zoom shouldn't be used at the same time.

**Comment by trvrb** [comment] 2017-02-25 22:35
I think this has been resolved in PR #208.

**Closed by trvrb** 2017-02-25 22:35 UTC
