### ISSUE TITLE
Blank metadata download

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#1411] opened 2021-10-03 22:48 UTC
**Current Behavior**  
For some datasets  or zoom levels, the downloaded per-strain metadata is a file with one line:

```
strain
```

**Expected behavior**  
The downloaded metadata should reflect all strains currently selected (i.e. in the header, "Showing X of Y genomes"). 

**How to reproduce**  
Steps to reproduce the current behavior:  

_Will add soon_

**Your environment: if browsing Nextstrain online**  
 - Operating system: MacOS 
 - Browser: Firefox 92.0
 - Auspice 2.31.0
 
**Additional context**  
* May be related to datasets without time.
* Seems to be stochastic

**Comment by corneliusroemer** [comment] 2021-10-04 21:52
I've just encountered this bug, too. It's definitely highly selective in when it happens. This is the tree where it occured:
https://nextstrain.org/groups/neherlab/ncov/global?branchLabel=aa&c=gt-ORF1b_1918&f_clade_membership=21A%20%28Delta%29&f_pango_lineage=AY.30&m=div

This is a screenshot where one can see the issue with `0 authors`:
![image](https://user-images.githubusercontent.com/25161793/135929897-fc4b0506-a40f-46f6-aa9c-4b812b077406.png)

**Comment by corneliusroemer** [comment] 2021-10-04 23:08
Now that I've thought a bit more about the issue, I'm pretty sure I've come up with one failure mode. Steps to reproduce (haven't done myself - but seems like a plausible hypothesis for me):
1. Load a nextstrain.org auspice in browser
2. Update dataset by using nextstrain deploy (try out two different scenarios: a) URL stays same but strain change, b) URL changes, e.g. dated build)
3. Try metadata download
4. Observe results

The failure is that auspice makes a query to the server for something that no longer exists. Rather than throwing an error to the user, it fails silently, confusing the user.

**Comment by corneliusroemer** [comment] 2023-07-27 12:07
Just have this happening again - very weird. Sometimes download is empty now (usually not the first download, but after browsing around) - sometimes it's the tips that were _previously_ highlighted (before I zoomed out via minus lens)

**Comment by corneliusroemer** [comment] 2023-07-27 12:19
Hah, I can reproduce it on this tree: https://next.nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2ff8b_f80b50.json?label=id:node_6763511

This node produces proper download:
<img width="878" alt="image" src="https://github.com/nextstrain/auspice/assets/25161793/b093968c-201f-4ffa-a4ff-33de595bca8c">

But this node results in empty download:
<img width="865" alt="image" src="https://github.com/nextstrain/auspice/assets/25161793/a3eab801-4cbe-4659-aec9-f4e9ed59f786">

I'll download the tree as it is not permanently saved by Usher (just delete the .txt, it's required for upload to Github): 
[subtreeAuspice1_genome_2ff8b_f80b50.json.txt](https://github.com/nextstrain/auspice/files/12183170/subtreeAuspice1_genome_2ff8b_f80b50.json.txt)

Here are some of the logs, not sure if this is helpful:
<img width="1321" alt="image" src="https://github.com/nextstrain/auspice/assets/25161793/bcf231f1-e0b1-44c9-8932-db67f97766b2">

Steps:
1. Load tree
2. Navigate to the first branch
3. Download
4. Observe that it's a 19kB metadata file
5. Navigate to second branch
6. Download and observe empty file
7. Navigate to first branch
8. Download and observe it's the same 19kB again
@jameshadfield

**Comment by corneliusroemer** [comment] 2023-07-27 12:23
I think I know what the issue is: it's a bug to do with the `label=id:node_6763511` parameter!

Here's what I found:

For some reason, when you open a tree with that label parameter, metadata will only ever output tips that are below the node that you loaded the tree with. So if you download metadata for that internal node, or any child node, all is fine.

However, as soon as you zoom out, you stop getting extra metadata, you will only ever get at most what's below that node (zoom out and observe that the file size remains the same). When you zoom to a different internal node that doesn't have the initial node as a child, this results in the intersection being _empty_, hence the empty metadata download.

**Comment by joverlee521** [comment] 2023-07-27 18:10
Wow, nice find @corneliusroemer! I am able to reproduce the bug by loading any tree with the `label` query param. 

The reason the nodes are being excluded in the metadata download is because the `node.inView` values are False and therefore [skipped in`strainTSV`](https://github.com/nextstrain/auspice/blob/3e3f8bd66af61d9aa082b50cc13e57c629d9a07e/src/components/download/helperFunctions.js#L224-L226). 

Now to trace down why the `inView` values are not getting updated when you zoom out.

**Comment by joverlee521** [comment] 2023-07-27 18:59
Hmm, @jameshadfield I will need a refresher on `node.inView` vs `node.shell.inView`. 

When clicking on "Reset Layout", [`updateVisibleTipsAndBranchThicknesses` gets dispatched](https://github.com/nextstrain/auspice/blob/3e3f8bd66af61d9aa082b50cc13e57c629d9a07e/src/components/tree/tree.js#L40) and calls on `applyInViewNodesToTree`. From what I can tell, this always sets the `node.shell.inView` property because I'm not sure when [`tree.nodes[0].shell` is ever a falsy value](https://github.com/nextstrain/auspice/blob/3e3f8bd66af61d9aa082b50cc13e57c629d9a07e/src/actions/tree.js#L26). 

The metadata download only checks the `node.inView` property but not `node.shell.inView`, so it's skipping the nodes even though they are marked as visible in `node.shell.inView`.

**Closed** 2023-08-20 21:56 UTC
Labels: bug
