### ISSUE TITLE
Download data: tree is broken

### ISSUE THREAD

**Issue by nicfel** [nextstrain/auspice#961] opened 2020-03-18 17:20 UTC
The tree's downloaded using the download data button are broken (i.e. don't open in either figtree or icytree). This applies to both divergence and timetree

**Comment by CameronDevine** [comment] 2020-03-18 18:17
@nicfel what format are you trying to download?

**Comment by nicfel** [comment] 2020-03-18 18:25
newick

**Comment by n1kio** [comment] 2020-03-21 13:26
@nicfel I can't reproduce this. I could open both newick trees with figtree v1.4.4 on macOS.

What version of figtree where you using?

**Comment by Fenrikur** [comment] 2020-03-21 14:16
Failed to reproduce the issue as well with current master (33ef6bccfc3ff92803a12f38848cfd7a04f1153d) and FigTree v1.4.4 on Windows (Java version 1.8.0_241) using datasets for ncov and zika for both tree and timetree exports in newick format.

**Comment by jameshadfield** [comment] 2020-03-26 03:09
Closing this as it can't be reproduced, but please re-open if this happens again (and please specify the dataset & auspice version used)

**Closed by jameshadfield** 2020-03-26 03:09 UTC
Labels: bug, good first issue, moderate priority, please take this issue, regression
